[package]
name = "terminal-wait-exit"
version = "1.0.1"
edition = "2021"
license = "MIT"
description = "wait user exit terminal, like Ctrl+C"
repository = "https://github.com/chen3cn/terminal-wait-exit"

[dependencies]
tokio = { version = "1.38", features = ["signal", "macros"] }
